apiVersion: v2
name: runaijob
version: 1.0.1
description: A Helm chart for RunAI Job
appVersion: "1.0"

dependencies:
  - name: runai-common
    version: 1.0.0
    repository: "file://../runai-common"