{{- define "runai-common.pvc" }}
{{- range $index, $pvcParam := .Values.persistentVolumes }}
{{- $pvcParamParts := split ":" $pvcParam }}
{{- if eq (len $pvcParamParts) 4 }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pvc.claim.name" (dict "pvcIndex" $index "pvcParam" $pvcParam "releaseName" $.Release.Name) }}
  labels:
  {{- include "runai-common.charts.label-addition" $ | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ $pvcParamParts._1 }}
  volumeMode: Filesystem
    {{- if len $pvcParamParts._0 }}
  storageClassName: {{ $pvcParamParts._0 }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}